### ISSUE TITLE
Implement heart-beating

### ISSUE THREAD

**Issue by pcan** [pcan/node-stomp-protocol#11]
From the spec:

## Heart-beating
Heart-beating can optionally be used to test the healthiness of the underlying TCP connection and to make sure that the remote end is alive and kicking.

In order to enable heart-beating, each party has to declare what it can do and what it would like the other party to do. This happens at the very beginning of the STOMP session, by adding a `heart-beat` header to the `CONNECT` and `CONNECTED` frames.

**Comment by sywka** [comment]
How soon will this functionality be planned?

**Comment by pcan** [comment]
I'll try to spend some time on this during the weekend, if I can. If you have any further suggestion, let me know.
