### ISSUE TITLE
What is the reason that maxBufferSize is set initially to just a 10K?

### ISSUE THREAD

**Issue by gsbelarus** [pcan/node-stomp-protocol#31]
Is it possible to include this parameter into the list of `StompFrameLayer` class constructor params? So, it could be configured at the time of stomp protocol classes instantiation?

Or there are some strict limitations imposed by the stomp protocol specifications?

**Comment by pcan** [comment]
It's just a default value that has been set initially. Of course, we may add a new `maxBufferSize` field to `StompConfig` and use it in `StompFrameLayer.init`. Feel free to submit a PR for this improvement.

**Comment by gsbelarus** [comment]
I did. Please, merge the PR and publish new version of the library. Many thanks!

**Comment by pcan** [comment]
Just published `0.4.6` on npm.
