### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by yoruvo** [pcan/node-stomp-protocol#39]
Hi,

from the perspective of a complete newcomer to the topic of message brokers and networking, I am not able to understand the scope or use case of this project.

I was able to set up a Websocket-based server by viewing issue #18 and combining it with code from the README.

I have a client based on `@stomp/stompjs` which was able to connect to this server.

However, nothing happens upon the connection besides both the client & the server acknowledging that a connection happened. The client disconnects after 10 seconds, probably due to not receive a response from the server.

As this is supposed to be an API for handling the STOMP protocol, I expected to have some kind of helping hand in sending the response CONNECTED frame. In the TypeScript def files of the module, I can see tyspes like StompProtocolHandlerV12, of type StompProtocolHandler, which in turn has `client` and `server` children containing StompCommands.

However, the documentation has no description of these things, and if these types are somehow usable to send responses from the server to the client, I cannot find where to access such functions.

Am I misunderstanding the use and meaning of this library? Am I supposed to manually compose my "server response frames" after the library helped me accept the connection from the client? The README does not tell me this.

Please advise.

Thanks for your hard work,
ivi

P.S.: Instructions on connecting this library to an Express-based server rather than a raw socket would be appreciated, if that is even possible.

**Comment by pcan** [comment]
Hi @yoruvo,

this library is meant as an implementation of the STOMP protocol from a low-level perspective. As reported in the readme, the goal is **not** an implementation of a fully functional broker, but only the framing layer of the protocol itself. The behaviour of the server side as a proper broker is up to the user of this library. Said that, there is a [branch](https://github.com/pcan/node-stomp-protocol/tree/broker-layer) I was starting working on that aimed to fill this gap, but unfortunately I didn't have time to complete.
Hope this answers your question :)

Thanks for your interest!
